### ISSUE TITLE
SB1 Projects with Comments Don't Load

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-sb1-converter#36]
### Expected Behavior

Project 658960 should load.

### Actual Behavior

It doesn't load in 3.0 but does in 2.0. The console shows the following errors:

```
projects.bundle.js:31 vm Couldn't find SB2 block: scratchComment
(anonymous) @ projects.bundle.js:31
projects.bundle.js:31 Error: Error in Scratch GUI [location=https://scratch.mit.edu/projects/658960/editor]: TypeError: Cannot read property 'assetMatchesBase' of undefined
    at t.value (projects.bundle.js:153)
    at u (common.bundle.js:22)
    at beginWork (common.bundle.js:22)
    at o (common.bundle.js:22)
    at i (common.bundle.js:22)
    at s (common.bundle.js:22)
    at b (common.bundle.js:22)
    at T (common.bundle.js:22)
    at f (common.bundle.js:22)
    at p (common.bundle.js:22)
    at Object.enqueueSetState (common.bundle.js:22)
    at i.A.setState (projects.bundle.js:128)
    at i.onStateChange (projects.bundle.js:47)
    at Object.notify (projects.bundle.js:47)
    at e.notifyNestedSubs (projects.bundle.js:47)
    at i.onStateChange (projects.bundle.js:47)
    at Object.notify (projects.bundle.js:47)
    at e.notifyNestedSubs (projects.bundle.js:47)
    at i.onStateChange (projects.bundle.js:47)
    at Object.notify (projects.bundle.js:47)
    at e.notifyNestedSubs (projects.bundle.js:47)
    at i.onStateChange (projects.bundle.js:47)
    at Object.notify (projects.bundle.js:47)
    at e.notifyNestedSubs (projects.bundle.js:47)
    at i.onStateChange (projects.bundle.js:47)
    at Object.notify (common.bundle.js:30)
    at e.notifyNestedSubs (common.bundle.js:30)
    at d.onStateChange (common.bundle.js:16)
    at Object.h [as dispatch] (common.bundle.js:16)
    at e (<anonymous>:1:40553)
    at projects.bundle.js:120
    at Object.dispatch (common.bundle.js:38)
    at dispatch (<anonymous>:1:28545)
    at Object.onError (projects.bundle.js:153)
    at projects.bundle.js:153
(anonymous) @ projects.bundle.js:31
projects.bundle.js:31 gui Unhandled Error: Error: Error in Scratch GUI [location=https://scratch.mit.edu/projects/658960/editor]: TypeError: Cannot read property 'assetMatchesBase' of undefined    at t.value (https://scratch.mit.edu/js/projects.bundle.js:153:2740958)    at u (https://scratch.mit.edu/js/common.bundle.js:22:512321)    at beginWork (https://scratch.mit.edu/js/common.bundle.js:22:514039)    at o (https://scratch.mit.edu/js/common.bundle.js:22:526160)    at i (https://scratch.mit.edu/js/common.bundle.js:22:526481)    at s (https://scratch.mit.edu/js/common.bundle.js:22:526719)    at b (https://scratch.mit.edu/js/common.bundle.js:22:530262)    at T (https://scratch.mit.edu/js/common.bundle.js:22:529999)    at f (https://scratch.mit.edu/js/common.bundle.js:22:529127)    at p (https://scratch.mit.edu/js/common.bundle.js:22:528517)    at Object.enqueueSetState (https://scratch.mit.edu/js/common.bundle.js:22:503098)    at i.A.setState (https://scratch.mit.edu/js/projects.bundle.js:128:570)    at i.onStateChange (https://scratch.mit.edu/js/projects.bundle.js:47:12805)    at Object.notify (https://scratch.mit.edu/js/projects.bundle.js:47:8906)    at e.notifyNestedSubs (https://scratch.mit.edu/js/projects.bundle.js:47:17664)    at i.onStateChange (https://scratch.mit.edu/js/projects.bundle.js:47:12823)    at Object.notify (https://scratch.mit.edu/js/projects.bundle.js:47:8906)    at e.notifyNestedSubs (https://scratch.mit.edu/js/projects.bundle.js:47:17664)    at i.onStateChange (https://scratch.mit.edu/js/projects.bundle.js:47:12823)    at Object.notify (https://scratch.mit.edu/js/projects.bundle.js:47:8906)    at e.notifyNestedSubs (https://scratch.mit.edu/js/projects.bundle.js:47:17664)    at i.onStateChange (https://scratch.mit.edu/js/projects.bundle.js:47:12823)    at Object.notify (https://scratch.mit.edu/js/projects.bundle.js:47:8906)    at e.notifyNestedSubs (https://scratch.mit.edu/js/projects.bundle.js:47:17664)    at i.onStateChange (https://scratch.mit.edu/js/projects.bundle.js:47:12823)    at Object.notify (https://scratch.mit.edu/js/common.bundle.js:30:479912)    at e.notifyNestedSubs (https://scratch.mit.edu/js/common.bundle.js:30:480440)    at d.onStateChange (https://scratch.mit.edu/js/common.bundle.js:16:18609)    at Object.h [as dispatch] (https://scratch.mit.edu/js/common.bundle.js:16:21734)    at e (<anonymous>:1:40553)    at https://scratch.mit.edu/js/projects.bundle.js:120:27087    at Object.dispatch (https://scratch.mit.edu/js/common.bundle.js:38:2390)    at dispatch (<anonymous>:1:28545)    at Object.onError (https://scratch.mit.edu/js/projects.bundle.js:153:495583)    at https://scratch.mit.edu/js/projects.bundle.js:153:494242Component stack:     in t    in Connect(t)    in InjectIntl(Connect(t))    in n    in Connect(n)    in n    in Connect(n)    in n    in Connect(n)    in n    in Connect(n)    in n    in Connect(n)    in InjectIntl(Connect(n))    in n    in Connect(n)    in n    in Connect(n)    in t    in Connect(t)    in Unknown    in IntlProvider    in Connect(IntlProvider)    in n    in Connect(n)    in InjectIntl(Connect(n))    in t    in Connect(t)    in IntlProvider    in r
(anonymous) @ projects.bundle.js:31
projects.bundle.js:87 Uncaught (in promise) TypeError: Cannot read property 'assetMatchesBase' of undefined
    at projects.bundle.js:87
```

**Comment by ArnoHue** [comment]
It seems to be bit of a pity to me that his is not being addressed (most likely an easy fix?). At least judging from the JavaScript error callstack, this bug causes https://scratch.mit.edu/projects/569176/ ("Chess") to fail when loading on Chrome. After I remixed it on Firefox, it worked on Chrome again as well. The author does not seem to be active any more, but every day several Scratchers comment (and I suppose a lot more try) as it was widely used in the Scratch 1 and 2 days. There literally must be something like 1000 comments now, with Scratchers wondering why it stopped working. And for sure there are more projects affected.
